language: ruby
services:
- docker
install: bundle install --without="development"
script: rake container:build_testing && rake tests:run_all
before_deploy: bash ./scripts/ci/before_deploy.sh
deploy:
  provider: script
  script: bash ./scripts/ci/deploy.sh
  on:
    branch: master
