language: ruby
services:
  - docker
install: bundle install --without="development"
before_script:
  - rake docker:build_testing
script:
  - rake tests:run_all
deploy:
  provider: script
  script: rake docker:build_push_prod
  on:
    branch: master
