version: '3'
services:
  devel:
    image: muell_dev
    restart: always
    depends_on:
      - "mysql"
    environment:
      ENABLE_DEBUG: 0
      ICSBOT_ENV: development
    env_file:
      - ./docker/development.env
    volumes:
      - .:/app:rw
      - ./db:/db:ro
      - ./assets:/assets:ro
      - ./log:/log:rw
    networks:
      - backend
    ports:
      - 1234:1234
      - 26162:26162
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - backend
    volumes:
      - ./db/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
networks:
  backend:
    driver: bridge
