version: '3'
services:
  app:
    build: ./docker/app/
    volumes:
      - .:/app:rw
      - ./assets:/assets:ro
      - ./db:/db:rw
    networks:
      - frontend
  migrations:
    build: ./docker/migrations/
    volumes:
      - ./db:/db:rw
    restart: on-failure
    environment:
      - DATABASE_URL=mysql://root:example@muell_mysql_1/icstelegrambot
    networks:
      - frontend
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - test
    networks:
      - frontend
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    networks:
      - test
    environment:
      - PMA_HOST=muell_mysql_1  
    networks:
      - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
