version: '3'
services:
  prod:
    image: benjaminsattler/icstelegrambot
    restart: always
    env_file:
      # create this file by copying ./docker/environment.env.example
      - ./docker/production.env
    volumes:
      # volume for ics file storage
      - ./assets:/assets:rw
      # volume for log files
      - ./log:/log:rw
