version: '3'
services:
  muell-devel:
    build:
      context: .
      dockerfile: ./docker/app-devel/Dockerfile
    restart: always
    env_file:
      - ./docker/app-devel/docker.env
    volumes:
      - .:/app:rw
      - ./assets:/assets:ro
      - ./db:/db:rw
      - ./log:/log:rw
    networks:
      - frontend
    ports:
      - 1234:1234
      - 26162:26162
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - frontend
      - backend
    volumes:
      - ./db/mysql:/var/lib/mysql
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
