version: '3'
services:
  app:
    build: .
    restart: always
    volumes:
      - .:/app:rw
      - ./assets:/assets:ro
      - ./db:/db:rw
      - ./log:/log:rw
    networks:
      - frontend
    ports:
      - 1234:1234
      - 26162:26162
    environment:
      - ICSBOT_ENV=testing
  migrations:
    build: ./docker/migrations/
    volumes:
      - ./db:/db:rw
    restart: on-failure
    environment:
      - DATABASE_URL=mysql://root:example@muell_mysql_1/icstelegrambot
    networks:
      - frontend
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - frontend
      - backend
    volumes:
      - ./db/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    networks:
      - test
    environment:
      - PMA_HOST=muell_mysql_1  
    networks:
      - backend
  rspec:
    build:
      context: ./
      dockerfile: ./docker/rspec/Dockerfile
    volumes:
      - .:/app
  rubocop:
    build: ./docker/rubocop/
    volumes:
      - .:/app
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
