version: '3'
services:
  app:
    build: .
    restart: always
    env_file:
      - ./docker/app/docker.env
    volumes:
      - .:/app:rw
      - ./assets:/assets:ro
      - ./db:/db:rw
      - ./log:/log:rw
    networks:
      - frontend
    ports:
      - 1234:1234
      - 26162:26162
    environment:
      - ICSBOT_ENV=testing
  migrations:
    build: ./docker/migrations/
    volumes:
      - ./db:/db:rw
    restart: on-failure
    env_file:
      - ./docker/migrations/docker.env
    networks:
      - backend
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - frontend
      - backend
    volumes:
      - ./db/mysql:/var/lib/mysql
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
