---
# This file needs to be preprocessed before
# the dev deployment may be deployed to the
# cluster.
# The following rake task will take care of
# things for you:
#
# $ rake k8s:generate_dev_deployment
#
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  creationTimestamp: null
  name: "devel"
  labels:
    app: "development"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "development"
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: "development"
    spec:
      containers:
      - env:
        - name: ADMIN_USERS
          valueFrom:
            configMapKeyRef:
              key: ADMIN_USERS
              name: development-config
        - name: BOT_TOKEN
          valueFrom:
            configMapKeyRef:
              key: BOT_TOKEN
              name: development-config
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URL
              name: development-config
        - name: ENABLE_DEBUG
          valueFrom:
            configMapKeyRef:
              key: ENABLE_DEBUG
              name: development-config
        - name: FLUSH_INTERVAL
          valueFrom:
            configMapKeyRef:
              key: FLUSH_INTERVAL
              name: development-config
        - name: ICSBOT_ENV
          value: development
        - name: MIGRATIONS_DIR
          valueFrom:
            configMapKeyRef:
              key: MIGRATIONS_DIR
              name: development-config
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: development-config
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              key: MYSQL_HOST
              name: development-config
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PASSWORD
              name: development-config
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PORT
              name: development-config
        - name: MYSQL_USERNAME
          valueFrom:
            configMapKeyRef:
              key: MYSQL_USERNAME
              name: development-config
        - name: PERSISTENCE
          valueFrom:
            configMapKeyRef:
              key: PERSISTENCE
              name: development-config
        - name: SQLITE_DB_PATH
          valueFrom:
            configMapKeyRef:
              key: SQLITE_DB_PATH
              name: development-config
        - name: TIMEZONE
          valueFrom:
            configMapKeyRef:
              key: TIMEZONE
              name: development-config
        - name: LOGGERS
          valueFrom:
            configMapKeyRef:
              key: LOGGERS
              name: development-config
        - name: GOOGLECLOUDLOGGER_PROJECT
          valueFrom:
            configMapKeyRef:
              key: GOOGLECLOUDLOGGER_PROJECT
              name: development-config
        - name: GOOGLECLOUDLOGGER_LOGNAME
          valueFrom:
            configMapKeyRef:
              key: GOOGLECLOUDLOGGER_LOGNAME
              name: development-config
        - name: GOOGLECLOUDLOGGER_RESOURCE_TYPE
          valueFrom:
            configMapKeyRef:
              key: GOOGLECLOUDLOGGER_RESOURCE_TYPE
              name: development-config
        - name: GOOGLECLOUDLOGGER_ENVIRONMENT
          value: development
        image: muell_dev
        imagePullPolicy: Never
        name: devel
        ports:
        - containerPort: 1234
        - containerPort: 26162
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: app-pv
        - mountPath: /db
          name: db-pv
          readOnly: true
        - mountPath: /assets
          name: assets-pv
      restartPolicy: Always
      volumes:
      - name: app-pv
        hostPath:
          path: {{ PROJECT_BASEPATH }}/
      - name: db-pv
        hostPath:
          path: {{ PROJECT_BASEPATH }}/db/
      - name: assets-pv
        hostPath:
          path: {{ PROJECT_BASEPATH }}/assets/
status: {}
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  creationTimestamp: null
  name: "mysql-development"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "mysql-development"
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: "mysql-development"
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: example
        args:
        - --default-authentication-plugin=mysql_native_password
        image: mysql:8.0
        name: mysql
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-pv
      volumes:
      - name: db-pv
        hostPath:
          path: {{ PROJECT_BASEPATH }}/db/mysql/
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: rdebug
spec:
  type: "NodePort"
  ports:
  - name: "1234"
    port: 1234
    targetPort: 1234
    nodePort: 31234
  - name: "26162"
    port: 26162
    targetPort: 26162
  selector:
    app: "development"
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: mysql-devel
spec:
  type: "NodePort"
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
    nodePort: 31235
  selector:
    app: "mysql-development"
status:
  loadBalancer: {}
