#!/bin/sh

answer=0
editor=`git config --get core.editor`
if [ "$editor" == "" ]; then
	editor=${FCEDIT:-${VISUAL:-${EDITOR:-vi}}}
fi
function getAnswer {
	while true; do
		echo "$1 (y/n)"
		answer=0
		read -r line
		case "$line" in
			y)
				answer=1
				break
				;;
			n)
				break 
				;;
			*)
				echo "I did not understand your input... Try again"
				;;
		esac
	done
}

echo "Running post-merge git hook..."
marker="###### EVERYTHING BELOW THIS LINE WILL BE REMOVED #####"
diff=`git diff HEAD@{1}..HEAD config/conf.yml.example`
confdir='config/'
if [ "$diff" = "" ]; then
        echo "Sample config is identical, no config file updates required"
else
	getAnswer "Sample config changed. Do you want to update each config file?"
	if [ "$answer" -eq "0" ]; then
		echo "Not updating configs."
		exit
	fi
	echo "Updating configs."
	exec < /dev/tty
	for conffile in ${confdir}*.yml
	do
		echo "Processing $conffile file.."
		tmpfile=`mktemp`
		backupfile=${confdir}backup/`basename $conffile .yml`_`date +%Y%m%d_%H%M%S`.yml
		mkdir -p `dirname $backupfile`
		oldfilesize=`wc -c < $conffile | sed 's/^ *//;s/ *$//'`
		echo "Working with temp file $tmpfile"
		cat $conffile > $tmpfile
		echo $marker >> $tmpfile
		echo "# Below you see the changes in the sample config." >> $tmpfile
		echo "# Please readjust your config file $conffile above" >> $tmpfile
		echo "# and then save and close the editor. Your config" >> $tmpfile
		echo "# will then automatically be updated accordingly." >> $tmpfile
		echo "$diff" >> $tmpfile
		$editor $tmpfile
		echo "Backing original config $conffile to $backupfile"
		cp $conffile $backupfile
		echo "Replacing config file $conffile"
		cp /dev/null $conffile
		while read -r line
		do
			if [ "$line" == "$marker" ]; then
				break
			fi
			echo "$line" >> $conffile
		done < $tmpfile
		newfilesize=`wc -c < $conffile | sed 's/^ *//;s/ *$//'`
		echo "Replaced config file $conffile. New filesize is $newfilesize bytes (`expr $newfilesize - $oldfilesize` bytes)"
		getAnswer "Continue with the next config file?"
		if [ "$answer" -eq "0" ]; then
			echo "Not continuing."
			break
		fi
	done
	echo "Finished updating config files."
fi 
