#!/bin/sh

echo Running pre commit hook.

git stash -u --keep-index

docker build $PWD/docker/rubocop
docker run --rm --volume "$PWD:/app" cagedata/rubocop && rspec
result=$?

git clean -df
git checkout -- .
git stash pop -q

exit $result
