#!/bin/sh

echo Running pre commit hook.

git stash -u --keep-index

docker run --rm --volume "$PWD:/app" muell_rubocop && docker run --rm --volume "$PWD:/app" muell_rspec
result=$?

git clean -df
git checkout -- .
git stash pop -q

exit $result
